#' Generate the printable pdf syllabus from the master syllabus
#'
#' `index.Rmd` is the MASTER copy of the syllabus. This script derives the
#' pdf-flavoured source (`index_syllabus_pdf.Rmd`) from it and renders
#' `index_syllabus_pdf.pdf`, which is the version students download and the
#' version shared with the department front office for archival.
#'
#' Keeping the pdf a *derived* product means the two versions cannot drift
#' apart: edit `index.Rmd` only, then re-run this script.
#'
#' Usage (from the project root):
#'   Rscript make_syllabus_pdf.R

master <- "index.Rmd"
derived <- "index_syllabus_pdf.Rmd"

stopifnot(file.exists(master))
x <- readLines(master, warn = FALSE)

## ---------------------------------------------------------------------------
## 1. Swap the html output block in the YAML header for a pdf one
## ---------------------------------------------------------------------------
yaml_ends <- grep("^---\\s*$", x)[1:2]
yaml <- x[yaml_ends[1]:yaml_ends[2]]

out_start <- grep("^output:\\s*$", yaml)
# the output block runs until the next top-level (non-indented) YAML key
rest <- grep("^[^[:space:]#]", yaml)
out_end <- min(rest[rest > out_start]) - 1L

pdf_output <- c(
  "output:",
  "  bookdown::pdf_document2:",
  "    toc: yes",
  "    toc_depth: 2",
  "    number_sections: yes",
  "    geometry: margin=1in",
  "    keep_tex: yes"
)

yaml <- c(yaml[seq_len(out_start - 1L)], pdf_output, yaml[(out_end + 1L):length(yaml)])
x <- c(yaml, x[(yaml_ends[2] + 1L):length(x)])

## ---------------------------------------------------------------------------
## 2. Strip html-only scaffolding that does not survive the LaTeX writer
## ---------------------------------------------------------------------------

# the jQuery chunk that injects the Boise State logo into the html header
js_start <- grep("^```\\{js logo-js", x)
if (length(js_start)) {
  js_end <- js_start + which(grepl("^```\\s*$", x[(js_start + 1L):length(x)]))[1]
  x <- x[-(js_start:js_end)]
}

# The right-aligned links at the top of the page ("Download pdf version", "Raw
# data on GitHub") are html navigation affordances. In the pdf the first is
# self-referential and the second would dangle on its own line after the table
# of contents, so drop both -- the Course Information section carries the same
# two links in prose.
x <- x[!grepl('^<div style="text-align: right">', x)]

# named anchors: `<a name="X"></a>Heading {#X}` -> `Heading {#X}`
x <- gsub('<a name="[^"]*"></a>', "", x)

# raw <a href="..." target="_blank">text</a> -> [text](...)
x <- gsub('<a href="([^"]*)"[^>]*>(.*?)</a>', "[\\2](\\1)", x, perl = TRUE)

## ---------------------------------------------------------------------------
## 3. Make site-relative links absolute
##
## Links such as `Timetable.html` resolve only when the file sits inside the
## rendered website. The pdf travels on its own -- students download it and the
## department front office archives it -- so those links must point at the
## published site instead of at a neighbouring file.
## ---------------------------------------------------------------------------
site <- "https://svenbuerki.github.io/EEB603_Reproducible_Science/"
x <- gsub("\\]\\((?!https?://|#|mailto:)([A-Za-z0-9_.-]+\\.(?:html|pdf))\\)",
          paste0("](", site, "\\1)"), x, perl = TRUE)

## ---------------------------------------------------------------------------
## 4. Table formatting: html-specific kable arguments -> LaTeX equivalents
## ---------------------------------------------------------------------------
x <- gsub(', format = "html"', "", x, fixed = TRUE)
x <- gsub('kable_styling(bootstrap_options = c("striped", "hover", "condensed"))',
          'kable_styling(latex_options = c("striped", "hold_position"))',
          x, fixed = TRUE)

## ---------------------------------------------------------------------------
## 5. Write the derived source and render it
## ---------------------------------------------------------------------------
header <- c(
  "<!-- DO NOT EDIT THIS FILE BY HAND.",
  "     It is generated from index.Rmd by make_syllabus_pdf.R.",
  "     Edit index.Rmd (the master syllabus) and re-run that script. -->",
  "",
  # start the body of the syllabus on a fresh page, after the table of contents
  "\\newpage",
  ""
)

# the comment must sit after the YAML header, not before it
yaml_ends <- grep("^---\\s*$", x)[1:2]
x <- append(x, header, after = yaml_ends[2])

writeLines(x, derived)
message("Wrote ", derived)

rmarkdown::render(derived, quiet = FALSE)
message("Wrote ", sub("\\.Rmd$", ".pdf", derived))
